name: A workflow for Coursework Group2 App
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.napier.coursework.UnitTestApp test
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: 5acf7dfe-ba00-4503-ad58-629e38b0a756 # not required for public repos
          directory: ./target/site/jacoco
          flags: UnitTests # optional
          verbose: true # optional (default = false)

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Set up Database Container
        run: |
          docker build -t database ./db 
          docker run --name world -dp 33060:3306 database
      - name: Integration Tests
        run: mvn -Dtest=com.napier.coursework.IntegrationTestApp test
      - name: Remove Database
        run: |
          docker stop world
          docker rm world
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: 5acf7dfe-ba00-4503-ad58-629e38b0a756 # not required for public repos
          directory: ./target/site/jacoco
          flags: IntegrationTests # optional
          verbose: true # optional (default = false)

  build:
    name: Coursework Group2 App Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit



